//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidateMe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValidateMe.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must has up to {1} days.
        /// </summary>
        public static string HasMoreThanNeededDays {
            get {
                return ResourceManager.GetString("HasMoreThanNeededDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must has up to {1} years.
        /// </summary>
        public static string HasMoreThanNeededYears {
            get {
                return ResourceManager.GetString("HasMoreThanNeededYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not contains any special character.
        /// </summary>
        public static string HasNoSpecialCharacters {
            get {
                return ResourceManager.GetString("HasNoSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must has at least {1} days until now.
        /// </summary>
        public static string HasNotEnoughDays {
            get {
                return ResourceManager.GetString("HasNotEnoughDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must has at least {1} years until now.
        /// </summary>
        public static string HasNotEnoughYears {
            get {
                return ResourceManager.GetString("HasNotEnoughYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must has exactly {1} characters.
        /// </summary>
        public static string HasNotExactLength {
            get {
                return ResourceManager.GetString("HasNotExactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contains at least {1} words.
        /// </summary>
        public static string HasNotMinimumWords {
            get {
                return ResourceManager.GetString("HasNotMinimumWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string HasNoValue {
            get {
                return ResourceManager.GetString("HasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was expected. Got {1} instead.
        /// </summary>
        public static string IncorrectType {
            get {
                return ResourceManager.GetString("IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be afternoon.
        /// </summary>
        public static string IsNotAfternoon {
            get {
                return ResourceManager.GetString("IsNotAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contains only letters.
        /// </summary>
        public static string IsNotAlphabetic {
            get {
                return ResourceManager.GetString("IsNotAlphabetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contains at least one letter and one number.
        /// </summary>
        public static string IsNotAlphanumeric {
            get {
                return ResourceManager.GetString("IsNotAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be dawn.
        /// </summary>
        public static string IsNotDawn {
            get {
                return ResourceManager.GetString("IsNotDawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be diffrent from {1}.
        /// </summary>
        public static string IsNotDifferentFrom {
            get {
                return ResourceManager.GetString("IsNotDifferentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email.
        /// </summary>
        public static string IsNotEmail {
            get {
                return ResourceManager.GetString("IsNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equals to {1}.
        /// </summary>
        public static string IsNotEqual {
            get {
                return ResourceManager.GetString("IsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be even.
        /// </summary>
        public static string IsNotEven {
            get {
                return ResourceManager.GetString("IsNotEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be evening.
        /// </summary>
        public static string IsNotEvening {
            get {
                return ResourceManager.GetString("IsNotEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater or equal to {1}.
        /// </summary>
        public static string IsNotGreaterOrEqualTo {
            get {
                return ResourceManager.GetString("IsNotGreaterOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1} {2}.
        /// </summary>
        public static string IsNotGreaterThan {
            get {
                return ResourceManager.GetString("IsNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in Guid format.
        /// </summary>
        public static string IsNotGuid {
            get {
                return ResourceManager.GetString("IsNotGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in the future.
        /// </summary>
        public static string IsNotInFuture {
            get {
                return ResourceManager.GetString("IsNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in last 24 hours.
        /// </summary>
        public static string IsNotInLast24Hours {
            get {
                return ResourceManager.GetString("IsNotInLast24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in the last 365 days.
        /// </summary>
        public static string IsNotInLast365Days {
            get {
                return ResourceManager.GetString("IsNotInLast365Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in next 24 hours.
        /// </summary>
        public static string IsNotInNext24Hours {
            get {
                return ResourceManager.GetString("IsNotInNext24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in the next 365 days.
        /// </summary>
        public static string IsNotInNext365Days {
            get {
                return ResourceManager.GetString("IsNotInNext365Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in the past.
        /// </summary>
        public static string IsNotInPast {
            get {
                return ResourceManager.GetString("IsNotInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a leap year.
        /// </summary>
        public static string IsNotLeapYear {
            get {
                return ResourceManager.GetString("IsNotLeapYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be more recent than {1}.
        /// </summary>
        public static string IsNotMoreRecentThan {
            get {
                return ResourceManager.GetString("IsNotMoreRecentThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be morning.
        /// </summary>
        public static string IsNotMorning {
            get {
                return ResourceManager.GetString("IsNotMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a negative number.
        /// </summary>
        public static string IsNotNegative {
            get {
                return ResourceManager.GetString("IsNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contains only numbers.
        /// </summary>
        public static string IsNotNumeric {
            get {
                return ResourceManager.GetString("IsNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be odd.
        /// </summary>
        public static string IsNotOdd {
            get {
                return ResourceManager.GetString("IsNotOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be older than {1}.
        /// </summary>
        public static string IsNotOlderThan {
            get {
                return ResourceManager.GetString("IsNotOlderThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a positive number.
        /// </summary>
        public static string IsNotPositive {
            get {
                return ResourceManager.GetString("IsNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not match our security patterns.
        /// </summary>
        public static string IsNotSafe {
            get {
                return ResourceManager.GetString("IsNotSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be smaller or equal to {1}.
        /// </summary>
        public static string IsNotSmallerOrEqualTo {
            get {
                return ResourceManager.GetString("IsNotSmallerOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be smaller than {1} {2}.
        /// </summary>
        public static string IsNotSmallerThan {
            get {
                return ResourceManager.GetString("IsNotSmallerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be today.
        /// </summary>
        public static string IsNotToday {
            get {
                return ResourceManager.GetString("IsNotToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be tomorrow.
        /// </summary>
        public static string IsNotTomorrow {
            get {
                return ResourceManager.GetString("IsNotTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be weekday.
        /// </summary>
        public static string IsNotWeekday {
            get {
                return ResourceManager.GetString("IsNotWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be weekend.
        /// </summary>
        public static string IsNotWeekend {
            get {
                return ResourceManager.GetString("IsNotWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be yesterday.
        /// </summary>
        public static string IsNotYesterday {
            get {
                return ResourceManager.GetString("IsNotYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be zero.
        /// </summary>
        public static string IsNotZero {
            get {
                return ResourceManager.GetString("IsNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not well formatted.
        /// </summary>
        public static string Misformatted {
            get {
                return ResourceManager.GetString("Misformatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value was expected but got null instead.
        /// </summary>
        public static string NullValueReceived {
            get {
                return ResourceManager.GetString("NullValueReceived", resourceCulture);
            }
        }
    }
}
